import Mathlib

/-!
# Quaternion algebras: beginnings — the algebra and its multiplication

We follow Voight, *Quaternion Algebras*, Chapter 2.  Throughout `F` is a field
with `char F ≠ 2` and `a, b ∈ Fˣ`.  Voight's `(a, b / F)` is Mathlib's
`ℍ[F, a, 0, b] = QuaternionAlgebra F a 0 b`, for which `i² = a`, `j² = b`,
`ij = k`, `ji = -k`.
-/

namespace QuaternionAlgebras

open scoped Quaternion

variable {F : Type*} [Field F] (a b : F)

/-- Standard generator `i = (0,1,0,0)` of `(a,b/F) = ℍ[F,a,0,b]`. -/
def gi : ℍ[F, a, 0, b] := ⟨0, 1, 0, 0⟩

/-- Standard generator `j = (0,0,1,0)` of `(a,b/F) = ℍ[F,a,0,b]`. -/
def gj : ℍ[F, a, 0, b] := ⟨0, 0, 1, 0⟩

/-- Derived standard generator `k = ij = (0,0,0,1)` of `(a,b/F) = ℍ[F,a,0,b]`. -/
def gk : ℍ[F, a, 0, b] := ⟨0, 0, 0, 1⟩

/-- The derived generator `k` is the product `ij`. -/
lemma gk_eq_gi_mul_gj : gk a b = gi a b * gj a b := by sorry

/-- Anticommutation of the standard generators: `ji = -ij`. -/
lemma gj_mul_gi : gj a b * gi a b = -(gi a b * gj a b) := by
  ext <;> simp [gi, gj]

/-- The square of `k = ij` is `-ab`. -/
lemma gk_sq : gk a b * gk a b = (-(a * b)) • (1 : ℍ[F, a, 0, b]) := by
  ext <;> simp [gk]

/-- The mixed products of the standard generators:
`ik = aj`, `ki = -aj`, `jk = -bi`, `kj = bi`. -/
lemma mul_table :
    gi a b * gk a b = a • gj a b ∧
    gk a b * gi a b = -(a • gj a b) ∧
    gj a b * gk a b = -(b • gi a b) ∧
    gk a b * gj a b = b • gi a b := by sorry

/-- `(a,b/F)` has dimension four as an `F`-vector space. -/
theorem dim_four : Module.finrank F ℍ[F, a, 0, b] = 4 :=
  QuaternionAlgebra.finrank_eq_four a 0 b

/-- The elements `1, i, j, k` are `F`-linearly independent: if
`t • 1 + x • i + y • j + z • k = 0` then `t = x = y = z = 0`.  (They moreover
form a basis, since the algebra has dimension four.) -/
lemma standard_basis_linearIndependent (t x y z : F)
    (h : t • (1 : ℍ[F, a, 0, b]) + x • gi a b + y • gj a b + z • gk a b = 0) :
    t = 0 ∧ x = 0 ∧ y = 0 ∧ z = 0 := by sorry

/-- Lifting generators to an algebra homomorphism: if an `F`-algebra `B` contains
`i', j'` with `(i')² = a`, `(j')² = b` and `j' i' = -i' j'`, then there is an
`F`-algebra homomorphism `(a,b/F) → B` sending `i ↦ i'`, `j ↦ j'`, `k ↦ i'j'`. -/
lemma lifthom_construction {B : Type*} [Ring B] [Algebra F B] (i' j' : B)
    (hi : i' * i' = algebraMap F B a) (hj : j' * j' = algebraMap F B b)
    (hji : j' * i' = -(i' * j')) :
    ∃ φ : ℍ[F, a, 0, b] →ₐ[F] B,
      φ (gi a b) = i' ∧ φ (gj a b) = j' ∧ φ (gk a b) = i' * j' := by sorry

/-- Standard generators presentation: if a finite-dimensional `F`-algebra `B` is
generated by nonzero `i', j'` with `(i')² = a`, `(j')² = b`, `i' j' = -j' i'`,
then `B ≅ (a,b/F)`. -/
lemma standard_generators_presentation {B : Type*} [Ring B] [Algebra F B]
    [Module.Finite F B] (i' j' : B) (hi0 : i' ≠ 0) (hj0 : j' ≠ 0)
    (hi : i' * i' = algebraMap F B a) (hj : j' * j' = algebraMap F B b)
    (hij : i' * j' = -(j' * i')) (hgen : Algebra.adjoin F {i', j'} = ⊤) :
    Nonempty (ℍ[F, a, 0, b] ≃ₐ[F] B) := by sorry

/-- Commuting with `i` kills the `j, k` parts: if `α i = i α` then
`α.imJ = α.imK = 0`. -/
lemma central_commute_i (ha : a ≠ 0) (htwo : (2 : F) ≠ 0) (α : ℍ[F, a, 0, b])
    (h : α * gi a b = gi a b * α) : α.imJ = 0 ∧ α.imK = 0 := by sorry

/-- Commuting with `j` kills the `i` part: if `α j = j α` then `α.imI = 0`. -/
lemma central_commute_j (hb : b ≠ 0) (htwo : (2 : F) ≠ 0) (α : ℍ[F, a, 0, b])
    (h : α * gj a b = gj a b * α) : α.imI = 0 := by sorry

/-- Centrality: `(a,b/F)` is central over `F`, i.e. its center is the image of
`F` (the bottom subalgebra). -/
theorem center_eq_bot (ha : a ≠ 0) (hb : b ≠ 0) (htwo : (2 : F) ≠ 0) :
    Subalgebra.center F ℍ[F, a, 0, b] = ⊥ := by sorry

end QuaternionAlgebras
