import Mathlib

/-!
# Quaternion algebras: beginnings — the algebra and its multiplication

We follow Voight, *Quaternion Algebras*, Chapter 2.  Throughout `F` is a field
with `char F ≠ 2` and `a, b ∈ Fˣ`.  Voight's `(a, b / F)` is Mathlib's
`ℍ[F, a, 0, b] = QuaternionAlgebra F a 0 b`, for which `i² = a`, `j² = b`,
`ij = k`, `ji = -k`.
-/

namespace QuaternionAlgebras

open scoped Quaternion

variable {F : Type*} [Field F] (a b : F)

/-- Standard generator `i = (0,1,0,0)` of `(a,b/F) = ℍ[F,a,0,b]`. -/
def gi : ℍ[F, a, 0, b] := ⟨0, 1, 0, 0⟩

/-- Standard generator `j = (0,0,1,0)` of `(a,b/F) = ℍ[F,a,0,b]`. -/
def gj : ℍ[F, a, 0, b] := ⟨0, 0, 1, 0⟩

/-- Derived standard generator `k = ij = (0,0,0,1)` of `(a,b/F) = ℍ[F,a,0,b]`. -/
def gk : ℍ[F, a, 0, b] := ⟨0, 0, 0, 1⟩

/-- The derived generator `k` is the product `ij`. -/
lemma gk_eq_gi_mul_gj : gk a b = gi a b * gj a b := by sorry

/-- Anticommutation of the standard generators: `ji = -ij`. -/
lemma gj_mul_gi : gj a b * gi a b = -(gi a b * gj a b) := by
  ext <;> simp [gi, gj]

/-- The square of `k = ij` is `-ab`. -/
lemma gk_sq : gk a b * gk a b = (-(a * b)) • (1 : ℍ[F, a, 0, b]) := by
  ext <;> simp [gk]

/-- The mixed products of the standard generators:
`ik = aj`, `ki = -aj`, `jk = -bi`, `kj = bi`. -/
lemma mul_table :
    gi a b * gk a b = a • gj a b ∧
    gk a b * gi a b = -(a • gj a b) ∧
    gj a b * gk a b = -(b • gi a b) ∧
    gk a b * gj a b = b • gi a b := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · ext <;> simp [gi, gj, gk]
  · ext <;> simp [gi, gj, gk]
  · ext <;> simp [gi, gj, gk]
  · ext <;> simp [gi, gj, gk]

/-- `(a,b/F)` has dimension four as an `F`-vector space. -/
theorem dim_four : Module.finrank F ℍ[F, a, 0, b] = 4 :=
  QuaternionAlgebra.finrank_eq_four a 0 b

/-- The elements `1, i, j, k` are `F`-linearly independent: if
`t • 1 + x • i + y • j + z • k = 0` then `t = x = y = z = 0`.  (They moreover
form a basis, since the algebra has dimension four.) -/
lemma standard_basis_linearIndependent (t x y z : F)
    (h : t • (1 : ℍ[F, a, 0, b]) + x • gi a b + y • gj a b + z • gk a b = 0) :
    t = 0 ∧ x = 0 ∧ y = 0 ∧ z = 0 := by
  have h' := congrArg (QuaternionAlgebra.linearEquivTuple a 0 b) h
  simp [LinearEquiv.map_add, LinearEquiv.map_zero,
    QuaternionAlgebra.coe_linearEquivTuple, QuaternionAlgebra.equivTuple_apply,
    gi, gj, gk] at h'
  exact h'

/-- Lifting generators to an algebra homomorphism: if an `F`-algebra `B` contains
`i', j'` with `(i')² = a`, `(j')² = b` and `j' i' = -i' j'`, then there is an
`F`-algebra homomorphism `(a,b/F) → B` sending `i ↦ i'`, `j ↦ j'`, `k ↦ i'j'`. -/
lemma lifthom_construction {B : Type*} [Ring B] [Algebra F B] (i' j' : B)
    (hi : i' * i' = algebraMap F B a) (hj : j' * j' = algebraMap F B b)
    (hji : j' * i' = -(i' * j')) :
    ∃ φ : ℍ[F, a, 0, b] →ₐ[F] B,
      φ (gi a b) = i' ∧ φ (gj a b) = j' ∧ φ (gk a b) = i' * j' := by
  let qb : QuaternionAlgebra.Basis B a 0 b :=
    { i := i'
      j := j'
      k := i' * j'
      i_mul_i := by
        simpa [Algebra.smul_def] using hi
      j_mul_j := by
        simpa [Algebra.smul_def] using hj
      i_mul_j := rfl
      j_mul_i := by
        simpa using hji
    }
  refine ⟨qb.liftHom, ?_, ?_, ?_⟩
  · simp [qb, gi, QuaternionAlgebra.Basis.liftHom_apply, QuaternionAlgebra.Basis.lift]
  · simp [qb, gj, QuaternionAlgebra.Basis.liftHom_apply, QuaternionAlgebra.Basis.lift]
  · simp [qb, gk, QuaternionAlgebra.Basis.liftHom_apply, QuaternionAlgebra.Basis.lift]

/-- Standard generators presentation (Voight 2.2.5): if an `F`-algebra `B` is
generated by nonzero `i', j'` with `(i')² = a`, `(j')² = b`, `i' j' = -j' i'`
(with `a, b ≠ 0` and `char F ≠ 2`), then `(a,b/F) ≃ₐ[F] B`.  Stated
constructively: the underlying map is `QuaternionAlgebra.Basis.liftHom` of the
basis `(i', j', i'j')`, upgraded to an isomorphism, so callers can use the
equivalence directly without routing through `Exists.choose`. -/
noncomputable def standard_generators_presentation {B : Type*} [Ring B] [Algebra F B]
    (ha : a ≠ 0) (hb : b ≠ 0) (htwo : (2 : F) ≠ 0)
    (i' j' : B) (hi0 : i' ≠ 0) (hj0 : j' ≠ 0)
    (hi : i' * i' = algebraMap F B a) (hj : j' * j' = algebraMap F B b)
    (hij : i' * j' = -(j' * i')) (hgen : Algebra.adjoin F {i', j'} = ⊤) :
    ℍ[F, a, 0, b] ≃ₐ[F] B := by
  haveI : Nontrivial B := nontrivial_of_ne i' 0 hi0
  have hji : j' * i' = -(i' * j') := by rw [hij, neg_neg]
  let qb : QuaternionAlgebra.Basis B a 0 b :=
    { i := i'
      j := j'
      k := i' * j'
      i_mul_i := by simpa [Algebra.smul_def] using hi
      j_mul_j := by simpa [Algebra.smul_def] using hj
      i_mul_j := rfl
      j_mul_i := by simpa using hji }
  set φ : ℍ[F, a, 0, b] →ₐ[F] B := qb.liftHom with hφ_def
  have hφi : φ (gi a b) = i' := by
    simp [hφ_def, qb, gi, QuaternionAlgebra.Basis.liftHom_apply, QuaternionAlgebra.Basis.lift]
  have hφj : φ (gj a b) = j' := by
    simp [hφ_def, qb, gj, QuaternionAlgebra.Basis.liftHom_apply, QuaternionAlgebra.Basis.lift]
  have hφk : φ (gk a b) = i' * j' := by
    simp [hφ_def, qb, gk, QuaternionAlgebra.Basis.liftHom_apply, QuaternionAlgebra.Basis.lift]
  -- Surjectivity: the range contains `i', j'`, which generate `B`.
  have hrange : φ.range = ⊤ := by
    rw [eq_top_iff, ← hgen]
    apply Algebra.adjoin_le
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · exact ⟨gi a b, hφi⟩
    · exact ⟨gj a b, hφj⟩
  have hsurj : Function.Surjective φ := by
    intro y
    have hy : y ∈ φ.range := by rw [hrange]; exact Algebra.mem_top
    obtain ⟨x, hx⟩ := hy
    exact ⟨x, hx⟩
  -- Multiplication facts in `B`.
  have m_ii : i' * i' = a • (1 : B) := by rw [hi, Algebra.algebraMap_eq_smul_one]
  have m_jj : j' * j' = b • (1 : B) := by rw [hj, Algebra.algebraMap_eq_smul_one]
  have m_ik : i' * (i' * j') = a • j' := by
    rw [← mul_assoc, m_ii, smul_mul_assoc, one_mul]
  have m_ki : (i' * j') * i' = -(a • j') := by
    rw [mul_assoc, hji, mul_neg, m_ik]
  have m_jk : j' * (i' * j') = -(b • i') := by
    rw [← mul_assoc, hji, neg_mul, mul_assoc, m_jj, mul_smul_comm, mul_one]
  have m_kj : (i' * j') * j' = b • i' := by
    rw [mul_assoc, m_jj, mul_smul_comm, mul_one]
  have m_kk : (i' * j') * (i' * j') = -((a * b) • (1 : B)) := by
    rw [← mul_assoc, m_ki, neg_mul, smul_mul_assoc, m_jj, smul_smul]
  -- Injectivity.
  have hinj : Function.Injective φ := by
    refine (injective_iff_map_eq_zero φ).2 fun α hα => ?_
    have hdecomp : α = α.re • (1 : ℍ[F, a, 0, b]) + α.imI • gi a b
        + α.imJ • gj a b + α.imK • gk a b := by
      apply QuaternionAlgebra.ext <;> simp [gi, gj, gk]
    have hφα : φ α = α.re • (1 : B) + α.imI • i' + α.imJ • j' + α.imK • (i' * j') := by
      conv_lhs => rw [hdecomp]
      simp only [map_add, map_smul, map_one, hφi, hφj, hφk]
    rw [hφα] at hα
    set e : B := α.re • (1 : B) + α.imI • i' + α.imJ • j' + α.imK • (i' * j') with he_def
    -- P1: factor out `2a`.
    have hP1 : (2 * a) • (α.re • (1 : B) + α.imI • i') = 0 := by
      have hexp : i' * (e * i' + i' * e) = (2 * a) • (α.re • (1 : B) + α.imI • i') := by
        rw [he_def]
        simp only [mul_add, add_mul, smul_mul_assoc, mul_smul_comm, m_ii, m_ik, m_ki,
          hji, mul_one, one_mul, smul_smul, smul_neg, mul_neg]
        module
      rw [← hexp, hα]; simp
    -- P2: factor out `2b`.
    have hP2 : (2 * b) • (α.re • (1 : B) + α.imJ • j') = 0 := by
      have hexp : j' * (e * j' + j' * e) = (2 * b) • (α.re • (1 : B) + α.imJ • j') := by
        rw [he_def]
        simp only [mul_add, add_mul, smul_mul_assoc, mul_smul_comm, m_jj, m_jk, m_kj,
          hji, mul_one, one_mul, smul_smul, smul_neg, mul_neg]
        module
      rw [← hexp, hα]; simp
    -- P3: factor out `-(2ab)`.
    have hP3 : (-(2 * a * b)) • (α.re • (1 : B) + α.imK • (i' * j')) = 0 := by
      have hexp : (i' * j') * (e * (i' * j') + (i' * j') * e)
          = (-(2 * a * b)) • (α.re • (1 : B) + α.imK • (i' * j')) := by
        rw [he_def]
        simp only [mul_add, add_mul, smul_mul_assoc, mul_smul_comm, m_ik, m_ki, m_jk,
          m_kj, m_kk, mul_one, one_mul, smul_smul, smul_neg, neg_smul, mul_neg]
        module
      rw [← hexp, hα]; simp
    -- Cancel the nonzero scalars.
    have hQ1 : α.re • (1 : B) + α.imI • i' = 0 := by
      have h2a : (2 * a) ≠ 0 := mul_ne_zero htwo ha
      rw [← inv_smul_smul₀ h2a (α.re • (1 : B) + α.imI • i'), hP1, smul_zero]
    have hQ2 : α.re • (1 : B) + α.imJ • j' = 0 := by
      have h2b : (2 * b) ≠ 0 := mul_ne_zero htwo hb
      rw [← inv_smul_smul₀ h2b (α.re • (1 : B) + α.imJ • j'), hP2, smul_zero]
    have hQ3 : α.re • (1 : B) + α.imK • (i' * j') = 0 := by
      have h2ab : (-(2 * a * b)) ≠ 0 := neg_ne_zero.2 (mul_ne_zero (mul_ne_zero htwo ha) hb)
      rw [← inv_smul_smul₀ h2ab (α.re • (1 : B) + α.imK • (i' * j')), hP3, smul_zero]
    -- Recover the coordinates.
    have ht1 : (2 * α.re) • (1 : B) = 0 := by
      have hid : (2 * α.re) • (1 : B)
          = ((α.re • (1 : B) + α.imI • i') + (α.re • (1 : B) + α.imJ • j')
              + (α.re • (1 : B) + α.imK • (i' * j'))) - e := by
        rw [he_def]; module
      rw [hid, hQ1, hQ2, hQ3, hα]; module
    have ht0 : α.re = 0 := by
      by_contra hre
      have h2re : (2 * α.re) ≠ 0 := mul_ne_zero htwo hre
      have : (1 : B) = 0 := by
        rw [← inv_smul_smul₀ h2re (1 : B), ht1, smul_zero]
      exact one_ne_zero this
    have hx0 : α.imI = 0 := by
      rw [ht0, zero_smul, zero_add] at hQ1
      by_contra hx
      exact hi0 (by rw [← inv_smul_smul₀ hx i', hQ1, smul_zero])
    have hy0 : α.imJ = 0 := by
      rw [ht0, zero_smul, zero_add] at hQ2
      by_contra hy
      exact hj0 (by rw [← inv_smul_smul₀ hy j', hQ2, smul_zero])
    have hz0 : α.imK = 0 := by
      rw [ht0, zero_smul, zero_add] at hQ3
      have hij0 : i' * j' ≠ 0 := by
        intro h
        have hbi : b • i' = 0 := by rw [← m_kj, h, zero_mul]
        exact hi0 (by rw [← inv_smul_smul₀ hb i', hbi, smul_zero])
      by_contra hz
      exact hij0 (by rw [← inv_smul_smul₀ hz (i' * j'), hQ3, smul_zero])
    apply QuaternionAlgebra.ext <;> simp [ht0, hx0, hy0, hz0]
  exact AlgEquiv.ofBijective φ ⟨hinj, hsurj⟩

/-- Commuting with `i` kills the `j, k` parts: if `α i = i α` then
`α.imJ = α.imK = 0`. -/
lemma central_commute_i (ha : a ≠ 0) (htwo : (2 : F) ≠ 0) (α : ℍ[F, a, 0, b])
    (h : α * gi a b = gi a b * α) : α.imJ = 0 ∧ α.imK = 0 := by sorry

/-- Commuting with `j` kills the `i` part: if `α j = j α` then `α.imI = 0`. -/
lemma central_commute_j (hb : b ≠ 0) (htwo : (2 : F) ≠ 0) (α : ℍ[F, a, 0, b])
    (h : α * gj a b = gj a b * α) : α.imI = 0 := by sorry

/-- Centrality: `(a,b/F)` is central over `F`, i.e. its center is the image of
`F` (the bottom subalgebra). -/
theorem center_eq_bot (ha : a ≠ 0) (hb : b ≠ 0) (htwo : (2 : F) ≠ 0) :
    Subalgebra.center F ℍ[F, a, 0, b] = ⊥ := by sorry

end QuaternionAlgebras
