import Mathlib

/-!
# Quaternion algebras: beginnings — the algebra and its multiplication

We follow Voight, *Quaternion Algebras*, Chapter 2.  Throughout `F` is a field
with `char F ≠ 2` and `a, b ∈ Fˣ`.  Voight's `(a, b / F)` is Mathlib's
`ℍ[F, a, 0, b] = QuaternionAlgebra F a 0 b`, for which `i² = a`, `j² = b`,
`ij = k`, `ji = -k`.
-/

namespace QuaternionAlgebras

open scoped Quaternion

variable {F : Type*} [Field F] (a b : F)

/-- Standard generator `i = (0,1,0,0)` of `(a,b/F) = ℍ[F,a,0,b]`. -/
def gi : ℍ[F, a, 0, b] := ⟨0, 1, 0, 0⟩

/-- Standard generator `j = (0,0,1,0)` of `(a,b/F) = ℍ[F,a,0,b]`. -/
def gj : ℍ[F, a, 0, b] := ⟨0, 0, 1, 0⟩

/-- Derived standard generator `k = ij = (0,0,0,1)` of `(a,b/F) = ℍ[F,a,0,b]`. -/
def gk : ℍ[F, a, 0, b] := ⟨0, 0, 0, 1⟩

/-- The derived generator `k` is the product `ij`. -/
lemma gk_eq_gi_mul_gj : gk a b = gi a b * gj a b := by ext <;> simp [gi, gj, gk]

/-- `(a,b/F)` has dimension four as an `F`-vector space. -/
theorem dim_four : Module.finrank F ℍ[F, a, 0, b] = 4 :=
  QuaternionAlgebra.finrank_eq_four a 0 b

/-- Standard generators presentation (Voight 2.2.5): if an `F`-algebra `B` is
generated by nonzero `i', j'` with `(i')² = a`, `(j')² = b`, `i' j' = -j' i'`
(with `a, b ≠ 0`, `char F ≠ 2`), then `(a,b/F) ≃ₐ[F] B`, via the basis
`(i', j', i'j')`'s `liftHom` upgraded to an isomorphism. -/
noncomputable def standard_generators_presentation {B : Type*} [Ring B] [Algebra F B]
    (ha : a ≠ 0) (hb : b ≠ 0) (htwo : (2 : F) ≠ 0)
    (i' j' : B) (hi0 : i' ≠ 0) (hj0 : j' ≠ 0)
    (hi : i' * i' = algebraMap F B a) (hj : j' * j' = algebraMap F B b)
    (hij : i' * j' = -(j' * i')) (hgen : Algebra.adjoin F {i', j'} = ⊤) :
    ℍ[F, a, 0, b] ≃ₐ[F] B := by
  haveI : Nontrivial B := nontrivial_of_ne i' 0 hi0
  have hji : j' * i' = -(i' * j') := by rw [hij, neg_neg]
  let qb : QuaternionAlgebra.Basis B a 0 b :=
    { i := i'
      j := j'
      k := i' * j'
      i_mul_i := by simpa [Algebra.smul_def] using hi
      j_mul_j := by simpa [Algebra.smul_def] using hj
      i_mul_j := rfl
      j_mul_i := by simpa using hji }
  set φ : ℍ[F, a, 0, b] →ₐ[F] B := qb.liftHom with hφ_def
  have hφi : φ (gi a b) = i' := by
    simp [hφ_def, qb, gi, QuaternionAlgebra.Basis.liftHom_apply, QuaternionAlgebra.Basis.lift]
  have hφj : φ (gj a b) = j' := by
    simp [hφ_def, qb, gj, QuaternionAlgebra.Basis.liftHom_apply, QuaternionAlgebra.Basis.lift]
  have hφk : φ (gk a b) = i' * j' := by
    rw [gk_eq_gi_mul_gj, map_mul, hφi, hφj]
  have hrange : φ.range = ⊤ := by
    rw [eq_top_iff, ← hgen]
    refine Algebra.adjoin_le fun z hz => ?_
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    exacts [⟨gi a b, hφi⟩, ⟨gj a b, hφj⟩]
  have m_ii : i' * i' = a • (1 : B) := by rw [hi, Algebra.algebraMap_eq_smul_one]
  have m_jj : j' * j' = b • (1 : B) := by rw [hj, Algebra.algebraMap_eq_smul_one]
  have m_ik : i' * (i' * j') = a • j' := by
    rw [← mul_assoc, m_ii, smul_mul_assoc, one_mul]
  have m_ki : (i' * j') * i' = -(a • j') := by
    rw [mul_assoc, hji, mul_neg, m_ik]
  have m_jk : j' * (i' * j') = -(b • i') := by
    rw [← mul_assoc, hji, neg_mul, mul_assoc, m_jj, mul_smul_comm, mul_one]
  have m_kj : (i' * j') * j' = b • i' := by
    rw [mul_assoc, m_jj, mul_smul_comm, mul_one]
  have m_kk : (i' * j') * (i' * j') = -((a * b) • (1 : B)) := by
    rw [← mul_assoc, m_ki, neg_mul, smul_mul_assoc, m_jj, smul_smul]
  have hinj : Function.Injective φ := by
    refine (injective_iff_map_eq_zero φ).2 fun α hα => ?_
    have hdecomp : α = α.re • (1 : ℍ[F, a, 0, b]) + α.imI • gi a b
        + α.imJ • gj a b + α.imK • gk a b := by
      apply QuaternionAlgebra.ext <;> simp [gi, gj, gk]
    have hφα : φ α = α.re • (1 : B) + α.imI • i' + α.imJ • j' + α.imK • (i' * j') := by
      conv_lhs => rw [hdecomp]
      simp only [map_add, map_smul, map_one, hφi, hφj, hφk]
    rw [hφα] at hα
    set e : B := α.re • (1 : B) + α.imI • i' + α.imJ • j' + α.imK • (i' * j') with he_def
    have hP1 : (2 * a) • (α.re • (1 : B) + α.imI • i') = 0 := by
      have hexp : i' * (e * i' + i' * e) = (2 * a) • (α.re • (1 : B) + α.imI • i') := by
        rw [he_def]
        simp only [mul_add, add_mul, smul_mul_assoc, mul_smul_comm, m_ii, m_ik, m_ki,
          hji, mul_one, one_mul, smul_smul, smul_neg, mul_neg]
        module
      rw [← hexp, hα]; simp
    have hP2 : (2 * b) • (α.re • (1 : B) + α.imJ • j') = 0 := by
      have hexp : j' * (e * j' + j' * e) = (2 * b) • (α.re • (1 : B) + α.imJ • j') := by
        rw [he_def]
        simp only [mul_add, add_mul, smul_mul_assoc, mul_smul_comm, m_jj, m_jk, m_kj,
          hji, mul_one, one_mul, smul_smul, smul_neg, mul_neg]
        module
      rw [← hexp, hα]; simp
    have hP3 : (-(2 * a * b)) • (α.re • (1 : B) + α.imK • (i' * j')) = 0 := by
      have hexp : (i' * j') * (e * (i' * j') + (i' * j') * e)
          = (-(2 * a * b)) • (α.re • (1 : B) + α.imK • (i' * j')) := by
        rw [he_def]
        simp only [mul_add, add_mul, smul_mul_assoc, mul_smul_comm, m_ik, m_ki, m_jk,
          m_kj, m_kk, mul_one, one_mul, smul_smul, smul_neg, neg_smul, mul_neg]
        module
      rw [← hexp, hα]; simp
    have cancel : ∀ {c : F} (x : B), c ≠ 0 → c • x = 0 → x = 0 :=
      fun x hc hx => by rw [← inv_smul_smul₀ hc x, hx, smul_zero]
    have hQ1 : α.re • (1 : B) + α.imI • i' = 0 := cancel _ (mul_ne_zero htwo ha) hP1
    have hQ2 : α.re • (1 : B) + α.imJ • j' = 0 := cancel _ (mul_ne_zero htwo hb) hP2
    have hQ3 : α.re • (1 : B) + α.imK • (i' * j') = 0 :=
      cancel _ (neg_ne_zero.2 (mul_ne_zero (mul_ne_zero htwo ha) hb)) hP3
    have ht1 : (2 * α.re) • (1 : B) = 0 := by
      have hid : (2 * α.re) • (1 : B)
          = ((α.re • (1 : B) + α.imI • i') + (α.re • (1 : B) + α.imJ • j')
              + (α.re • (1 : B) + α.imK • (i' * j'))) - e := by
        rw [he_def]; module
      rw [hid, hQ1, hQ2, hQ3, hα]; module
    have ht0 : α.re = 0 := by
      by_contra hre; exact one_ne_zero (cancel _ (mul_ne_zero htwo hre) ht1)
    have hx0 : α.imI = 0 := by
      rw [ht0, zero_smul, zero_add] at hQ1
      by_contra hx; exact hi0 (cancel _ hx hQ1)
    have hy0 : α.imJ = 0 := by
      rw [ht0, zero_smul, zero_add] at hQ2
      by_contra hy; exact hj0 (cancel _ hy hQ2)
    have hz0 : α.imK = 0 := by
      rw [ht0, zero_smul, zero_add] at hQ3
      have hij0 : i' * j' ≠ 0 := fun h =>
        hi0 (cancel _ hb (by rw [← m_kj, h, zero_mul]))
      by_contra hz; exact hij0 (cancel _ hz hQ3)
    apply QuaternionAlgebra.ext <;> simp [ht0, hx0, hy0, hz0]
  exact AlgEquiv.ofBijective φ ⟨hinj, by rw [← AlgHom.range_eq_top]; exact hrange⟩

end QuaternionAlgebras
